# Generated by Django 3.1.5 on 2021-05-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='家庭作业')),
                ('wordinfo', models.TextField(max_length=21845, verbose_name='作业内容')),
            ],
            options={
                'verbose_name': '家庭作业',
                'verbose_name_plural': '家庭作业',
                'db_table': 'HomeWord',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('email', models.EmailField(max_length=40, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '用户名',
                'verbose_name_plural': '用户名',
                'db_table': 'User',
            },
        ),
    ]
