# Generated by Django 3.1.5 on 2021-05-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nihao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeword',
            name='type',
            field=models.IntegerField(default=2, max_length=10, verbose_name='课程类型'),
            preserve_default=False,
        ),
    ]
